build:
  environment:
    python: 3.8
  nodes:
    coverage:
      project_setup:
        override:
          - python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements_test.txt
            pip install -r requirements_dev.txt
      tests:
        override:
          - command: 'pytest'
            coverage:
              file: '.coverage'
              config_file: '.coveragerc'
              format: 'py-cc'
    analysis:
      project_setup:
        override:
          - pip install sklearn pandas numpy textblob nltk scipy
      tests:
        override:
          - py-scrutinizer-run
          -
            command: pylint-run
            use_website_config: true
    tests: true
checks:
  python:
    code_rating: true
    duplicate_code: true
filter:
  excluded_paths:
    - '*/tests/*'
  dependency_paths:
    - 'lib/*'
