build:
  environment:
    python: 3.6
  tests:
    before:
    - pip install pytest pytest-cov coverage
    - pip install -r requirements.txt
  nodes:
    analysis:
      project_setup:
        override:
        - pip install sklearn pandas numpy textblob nltk scipy
        tests:
          override:
          - py-scrutinizer-run
          - command: pylint-run
            use_website_config: true
    coverage:
      tests:
        before:
        - pip install pytest pytest-cov coverage coveralls
        - pip install -r requirements.txt
        override:
        - command: pytest tests --cov=tabpy
          coverage:
            file: '.coverage'
            config_file: '.coveragerc'
            format: 'py-cc'
checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - '*/test/*'
    dependency_paths:
        - 'lib/*'
