os: linux
language: python
python: 3.6
install:
    - python -m pip install --upgrade pip
    - pip install pytest pytest-cov coveralls
    - npm install -g markdownlint-cli
script:
    - pip install -e .
    - py.test tests/unit --cov=tabpy --cov-append
    - py.test tests/integration --cov=tabpy --cov-append
    - markdownlint .
after_success:
    - coveralls
