os: linux
language: python
python: 3.6
install:
    - pip install pytest pytest-cov coveralls
    - npm install -g markdownlint-cli
script:
    - pip install tabpy -e .
    - pytest tests/unit --cov=tabpy --cov-append
    - pytest tests/integration
    - markdownlint .
after_success:
    - coveralls
